# Production Docker Compose
# This version builds and runs the production-ready applications

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: openerm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  nats:
    image: nats:2-alpine
    ports:
      - '4222:4222'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env.local
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/openerm
      SHADOW_DATABASE_URL: postgres://postgres:postgres@postgres:5432/openerm_shadow
      REDIS_URL: redis://redis:6379/0
      NEXT_PUBLIC_API_URL: http://api:3001/api
    ports:
      - '3001:3000'
    depends_on:
      - postgres
      - redis
      - nats

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env.local
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  postgres_data: