export type Risk = {
  id: string;
  title: string;
  description: string | null;
  taxonomyId: string | null;
  cause: string | null;
  consequence: string | null;
  ownerId: string | null;
  inherentL: number;
  inherentI: number;
  residualL: number | null;
  residualI: number | null;
  residualScore: number | null;
  appetiteThreshold: number | null;
  keyRisk: boolean;
  appetiteBreached: boolean;
  status: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
};
